"""Observable metadata registry.

Each entry carries lightweight scientific and engineering metadata for use in
documentation generation and validation pipelines.
"""

OBSERVABLES = {
    "pt": {
        "irc_safe": True,
        "category": "kinematic",
        "description": "Transverse momentum",
        "depends_on": ["fourvector"],
        "complexity": "O(1)",
    },
    "mass": {
        "irc_safe": True,
        "category": "kinematic",
        "description": "Invariant mass",
        "depends_on": ["fourvector"],
        "complexity": "O(1)",
    },
    "eta": {
        "irc_safe": True,
        "category": "kinematic",
        "description": "Pseudorapidity",
        "depends_on": ["fourvector"],
        "complexity": "O(1)",
    },
    "phi": {
        "irc_safe": True,
        "category": "kinematic",
        "description": "Azimuthal angle",
        "depends_on": ["fourvector"],
        "complexity": "O(1)",
    },
    "delta_r": {
        "irc_safe": True,
        "category": "kinematic",
        "description": "Jet angular distance",
        "depends_on": ["eta", "phi"],
        "complexity": "O(1)",
    },
    "multiplicity": {
        "irc_safe": False,
        "category": "shape",
        "description": "Number of jet constituents",
        "depends_on": ["constituents"],
        "complexity": "O(1)",
    },
    "constituent_pt_sum": {
        "irc_safe": True,
        "category": "shape",
        "description": "Scalar sum of constituent pT",
        "depends_on": ["pt"],
        "complexity": "O(N)",
    },
    "leading_constituent_pt": {
        "irc_safe": False,
        "category": "shape",
        "description": "Maximum constituent pT",
        "depends_on": ["pt"],
        "complexity": "O(N)",
    },
    "leading_pt_fraction": {
        "irc_safe": False,
        "category": "shape",
        "description": "Leading constituent pT fraction",
        "depends_on": ["leading_constituent_pt", "constituent_pt_sum"],
        "complexity": "O(N)",
    },
    "jet_width": {
        "irc_safe": True,
        "category": "shape",
        "description": "pT-weighted radial width",
        "depends_on": ["eta", "phi", "pt"],
        "complexity": "O(N)",
    },
    "girth": {
        "irc_safe": True,
        "category": "shape",
        "description": "Alias of jet width",
        "depends_on": ["jet_width"],
        "complexity": "O(N)",
    },
    "radial_moment_2": {
        "irc_safe": True,
        "category": "shape",
        "description": "Second radial moment (beta=2)",
        "depends_on": ["eta", "phi", "pt"],
        "complexity": "O(N)",
    },
    "radial_moment_3": {
        "irc_safe": True,
        "category": "shape",
        "description": "Third radial moment (beta=3)",
        "depends_on": ["eta", "phi", "pt"],
        "complexity": "O(N)",
    },
    "lha": {
        "irc_safe": True,
        "category": "shape",
        "description": "Les Houches angularity",
        "depends_on": ["eta", "phi", "pt"],
        "complexity": "O(N)",
    },
    "thrust_angularity": {
        "irc_safe": True,
        "category": "shape",
        "description": "Generalized angularity lambda^1_2",
        "depends_on": ["eta", "phi", "pt"],
        "complexity": "O(N)",
    },
    "ptd_angularity": {
        "irc_safe": False,
        "category": "shape",
        "description": "Generalized angularity lambda^2_0",
        "depends_on": ["eta", "phi", "pt"],
        "complexity": "O(N)",
    },
    "ptd": {
        "irc_safe": False,
        "category": "shape",
        "description": "pT dispersion",
        "depends_on": ["pt"],
        "complexity": "O(N)",
    },
    "tau1": {
        "irc_safe": False,
        "category": "substructure",
        "description": "Proxy one-axis N-subjettiness",
        "depends_on": ["eta", "phi", "pt"],
        "complexity": "O(N)",
    },
    "tau2": {
        "irc_safe": False,
        "category": "substructure",
        "description": "Proxy two-axis N-subjettiness",
        "depends_on": ["eta", "phi", "pt"],
        "complexity": "O(N)",
    },
    "tau3": {
        "irc_safe": False,
        "category": "substructure",
        "description": "Proxy three-axis N-subjettiness",
        "depends_on": ["eta", "phi", "pt"],
        "complexity": "O(N)",
    },
    "tau21": {
        "irc_safe": False,
        "category": "substructure",
        "description": "Proxy N-subjettiness ratio tau2/tau1",
        "depends_on": ["tau2", "tau1"],
        "complexity": "O(N)",
    },
    "tau32": {
        "irc_safe": False,
        "category": "substructure",
        "description": "Proxy N-subjettiness ratio tau3/tau2",
        "depends_on": ["tau3", "tau2"],
        "complexity": "O(N)",
    },
    "e2": {
        "irc_safe": True,
        "category": "substructure",
        "description": "Two-point energy correlation",
        "depends_on": ["eta", "phi", "pt"],
        "complexity": "O(N^2)",
    },
    "e3": {
        "irc_safe": True,
        "category": "substructure",
        "description": "Three-point energy correlation",
        "depends_on": ["eta", "phi", "pt"],
        "complexity": "O(N^3)",
    },
    "c2": {
        "irc_safe": True,
        "category": "substructure",
        "description": "Energy correlator ratio C2 = e3/e2^2",
        "depends_on": ["e3", "e2"],
        "complexity": "O(N^3)",
    },
    "d2": {
        "irc_safe": True,
        "category": "substructure",
        "description": "Energy correlator ratio D2 = e3/e2^3",
        "depends_on": ["e3", "e2"],
        "complexity": "O(N^3)",
    },
    "soft_drop_zg_proxy": {
        "irc_safe": False,
        "category": "groomed",
        "description": "Soft Drop zg proxy from top-2 pT constituents",
        "depends_on": ["pt"],
        "complexity": "O(N)",
    },
    "soft_drop_rg_proxy": {
        "irc_safe": False,
        "category": "groomed",
        "description": "Soft Drop rg proxy from top-2 pT constituents",
        "depends_on": ["eta", "phi", "pt"],
        "complexity": "O(N)",
    },
    "soft_drop_pass_fraction_proxy": {
        "irc_safe": False,
        "category": "groomed",
        "description": "Binary Soft Drop pass proxy on hardest pair",
        "depends_on": ["soft_drop_zg_proxy", "soft_drop_rg_proxy"],
        "complexity": "O(N)",
    },
    "groomed_pair_mass_proxy": {
        "irc_safe": False,
        "category": "groomed",
        "description": "Invariant mass of top-2 pT constituent pair",
        "depends_on": ["mass", "pt"],
        "complexity": "O(N)",
    },
}
